# Generated by Django 5.0.3 on 2024-03-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Agricultural', 'Agricultural'), ('Commercial', 'Commercial'), ('Other', 'Other')], max_length=50),
        ),
    ]
