# Generated by Django 5.0.3 on 2024-03-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_dashboard', '0002_alter_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Profile Review Pending'), ('Approved', 'Agent Profile Approved'), ('Suspended', 'Agent Profile Suspended')], default='Pending', max_length=20),
        ),
    ]
