# Generated by Django 5.0.3 on 2024-03-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_dashboard', '0003_agentprofile_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='agent_profiles/'),
        ),
    ]
