# Generated by Django 5.0.3 on 2024-03-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_dashboard', '0005_property_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
